name: 📚 Documentation Improvement
description: Suggest improvements to our documentation
title: "📚 Documentation: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve our documentation!

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation are you suggesting improvements for?
      options:
        - README
        - Code comments
        - API documentation
        - Usage examples
        - Tutorials
        - Website content
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation you're referring to? (URL, file path, etc.)
      placeholder: "e.g., README.md, docs/usage.md, website URL"
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: What is the current documentation content that needs improvement?
      placeholder: "Copy and paste the relevant section or describe what exists currently..."
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What changes would you like to see in the documentation?
      placeholder: "Describe your suggestion or provide the exact wording you'd like to see..."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about your suggestion here.
      placeholder: "Any additional information that would help us understand your suggestion..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
