// tests/formatters/cssFormatter.test.js
const { formatCssValue, formatTokensToCss } = require('../../src/formatters/cssFormatter');
const InternalToken = require('../../src/core/InternalToken');

describe('cssFormatter', () => {
    describe('formatCssValue', () => {
        it('should format colors from object to hex/rgba', () => {
            expect(formatCssValue({ r: 255, g: 0, b: 0, a: 1 }, 'color')).toBe('#ff0000');
            expect(formatCssValue({ r: 0, g: 255, b: 0, a: 0.5 }, 'color')).toBe('rgba(0, 255, 0, 0.5)');
        });
        it('should keep color strings as is', () => {
            expect(formatCssValue('#ABC', 'color')).toBe('#ABC');
            expect(formatCssValue('blue', 'color')).toBe('blue');
        });
        it('should return strings as is (for custom props)', () => {
            expect(formatCssValue('hello world', 'string')).toBe('hello world');
            expect(formatCssValue('"already quoted"', 'string')).toBe('"already quoted"');
        });
        it('should return numbers and dimensions as strings', () => {
            expect(formatCssValue(16, 'number')).toBe('16');
            expect(formatCssValue('16px', 'dimension')).toBe('16px');
        });
    });

    describe('formatTokensToCss', () => {
        const tokens = [
            new InternalToken('color-primary', ['color', 'primary'], '#ff0000', 'color', 'Primary color', { source: 'test' }),
            new InternalToken('size-font-large', ['size', 'font', 'large'], '24px', 'dimension', 'Large font size', { source: 'test' }),
            new InternalToken('font-family-heading', ['font', 'family', 'heading'], 'Arial Black', 'string', 'Heading font', { source: 'test' }),
        ];

        it('should generate CSS custom properties with default :root selector', () => {
            const expectedCss = `// Generated by Tokman CLI - CSS Custom Properties

:root {
  /* Primary color */
  --color-primary: #ff0000;
  /* Large font size */
  --size-font-large: 24px;
  /* Heading font */
  --font-family-heading: Arial Black;
}
`;
            expect(formatTokensToCss(tokens)).toBe(expectedCss);
        });

        it('should generate CSS custom properties with a custom selector', () => {
            const options = { selector: '.my-theme' };
            const expectedCss = `// Generated by Tokman CLI - CSS Custom Properties

.my-theme {
  /* Primary color */
  --color-primary: #ff0000;
  /* Large font size */
  --size-font-large: 24px;
  /* Heading font */
  --font-family-heading: Arial Black;
}
`;
            expect(formatTokensToCss(tokens, options)).toBe(expectedCss);
        });

        it('should handle an empty token array', () => {
             const expectedCss = `// Generated by Tokman CLI - CSS Custom Properties

:root {
}
`;
            expect(formatTokensToCss([])).toBe(expectedCss);
        });
    });
});
