// tests/formatters/scssFormatter.test.js
const { describe, it } = require('node:test');
const assert = require('node:assert');
const { formatScssValue, formatTokensToScss } = require('../../src/formatters/scssFormatter');
const InternalToken = require('../../src/core/InternalToken');

describe('scssFormatter', () => {
    describe('formatScssValue', () => {
        it('should format colors from object to hex/rgba', () => {
            assert.strictEqual(formatScssValue({ r: 255, g: 0, b: 0, a: 1 }, 'color'), '#ff0000');
            assert.strictEqual(formatScssValue({ r: 0, g: 255, b: 0, a: 0.5 }, 'color'), 'rgba(0, 255, 0, 0.5)');
        });
        it('should keep color strings as is', () => {
            assert.strictEqual(formatScssValue('#ABC', 'color'), '#ABC');
            assert.strictEqual(formatScssValue('blue', 'color'), 'blue');
        });
        it('should quote strings', () => {
            assert.strictEqual(formatScssValue('hello world', 'string'), "'hello world'");
            assert.strictEqual(formatScssValue("it's quoted", 'string'), "'it\\'s quoted'");
        });
        it('should return numbers and dimensions as strings', () => {
            assert.strictEqual(formatScssValue(16, 'number'), '16');
            assert.strictEqual(formatScssValue('16px', 'dimension'), '16px');
        });
    });

    describe('formatTokensToScss', () => {
        const tokens = [
            new InternalToken('color-primary', ['color', 'primary'], '#ff0000', 'color', 'Primary color', { source: 'test' }),
            new InternalToken('size-font-large', ['size', 'font', 'large'], '24px', 'dimension', 'Large font size', { source: 'test' }),
            new InternalToken('font-family-heading', ['font', 'family', 'heading'], '"Arial Black"', 'string', 'Heading font', { source: 'test' }),
        ];

        it('should generate individual SCSS variables', () => {
            const expectedScss = `// Generated by Tokman CLI - SCSS Variables

// Primary color
\$color-primary: #ff0000;

// Large font size
\$size-font-large: 24px;

// Heading font
\$font-family-heading: '"Arial Black"';

`;
            assert.strictEqual(formatTokensToScss(tokens), expectedScss);
        });

        it('should generate an SCSS map when generateMap is true', () => {
            const options = { generateMap: true, mapName: 'my-tokens' };
            const expectedScss = `// Generated by Tokman CLI - SCSS Variables

\$my-tokens: (
  'color': (
    'primary': #ff0000
  ),
  'size': (
    'font': (
      'large': 24px
    )
  ),
  'font': (
    'family': (
      'heading': '"Arial Black"'
    )
  )
);
`;
            assert.strictEqual(formatTokensToScss(tokens, options), expectedScss);
        });
    });
});
